// @generated by tools/protocol-codegen/generate.mjs from protocol/core/v1/manifest.json and protocol/core/v1/schema.json.
// DO NOT EDIT MANUALLY.
// ignore_for_file: unused_element

import 'dart:convert';

final class ProtocolCodecException implements Exception {
  const ProtocolCodecException(this.path, this.message);

  final String path;
  final String message;

  @override
  String toString() => 'ProtocolCodecException at $path: $message';
}

Map<String, Object?> _object(Object? value, String path) {
  if (value is! Map) throw ProtocolCodecException(path, 'expected an object');
  final result = <String, Object?>{};
  for (final entry in value.entries) {
    if (entry.key is! String) throw ProtocolCodecException(path, 'object keys must be strings');
    result[entry.key as String] = entry.value;
  }
  return result;
}

void _expectKeys(Map<String, Object?> value, Set<String> allowed, String path) {
  for (final key in value.keys) {
    if (!allowed.contains(key)) throw ProtocolCodecException('$path.$key', 'unknown field');
  }
}

Object? _required(Map<String, Object?> value, String key, String path) {
  if (!value.containsKey(key)) throw ProtocolCodecException('$path.$key', 'required field is missing');
  return value[key];
}

Object? _nullValue(Object? value, String path) {
  if (value != null) throw ProtocolCodecException(path, 'expected null');
  return null;
}

String _string(Object? value, String path, {int? minLength, String? pattern}) {
  if (value is! String) throw ProtocolCodecException(path, 'expected a string');
  if (minLength != null && value.length < minLength) throw ProtocolCodecException(path, 'string is shorter than $minLength characters');
  if (pattern != null && !RegExp(pattern).hasMatch(value)) throw ProtocolCodecException(path, 'string does not match $pattern');
  return value;
}

int _integer(Object? value, String path, {int? minimum, int? maximum}) {
  if (value is! int) throw ProtocolCodecException(path, 'expected an integer');
  if (minimum != null && value < minimum) throw ProtocolCodecException(path, 'integer is below $minimum');
  if (maximum != null && value > maximum) throw ProtocolCodecException(path, 'integer is above $maximum');
  return value;
}

bool _boolean(Object? value, String path) {
  if (value is! bool) throw ProtocolCodecException(path, 'expected a boolean');
  return value;
}

Object? _jsonValue(Object? value, String path) {
  if (value == null || value is bool || value is num || value is String) return value;
  if (value is List) {
    return List<Object?>.unmodifiable(value.indexed.map((entry) => _jsonValue(entry.$2, '$path[${entry.$1}]')));
  }
  if (value is Map) {
    return Map<String, Object?>.unmodifiable(_object(value, path).map((key, item) => MapEntry(key, _jsonValue(item, '$path.$key'))));
  }
  throw ProtocolCodecException(path, 'expected a JSON value');
}

Map<String, Object?> _jsonObject(Object? value, String path) => _jsonValue(_object(value, path), path) as Map<String, Object?>;
Map<String, Object?> _encodeJsonObject(Map<String, Object?> value, String path) => _jsonObject(value, path);

Map<String, T> _freezeMap<T>(Map<String, T> values, String path, T Function(T, String) validate) {
  return Map<String, T>.unmodifiable(values.map((key, item) => MapEntry(key, validate(item, '$path.$key'))));
}

Map<String, T> _decodeMap<T>(Object? value, String path, T Function(Object?, String) decode) {
  final object = _object(value, path);
  return Map<String, T>.unmodifiable(object.map((key, item) => MapEntry(key, decode(item, '$path.$key'))));
}

List<T> _freezeList<T>(Iterable<T> values, String path, T Function(T, String) validate, {int? minItems, bool uniqueItems = false, required Object? Function(T) encodeItem}) {
  final result = List<T>.unmodifiable(values.indexed.map((entry) => validate(entry.$2, '$path[${entry.$1}]')));
  if (minItems != null && result.length < minItems) throw ProtocolCodecException(path, 'array has fewer than $minItems items');
  if (uniqueItems) {
    final encoded = result.map((item) => jsonEncode(encodeItem(item))).toSet();
    if (encoded.length != result.length) throw ProtocolCodecException(path, 'array contains duplicate items');
  }
  return result;
}

List<T> _decodeList<T>(Object? value, String path, T Function(Object?, String) decode, {int? minItems, bool uniqueItems = false, required Object? Function(T) encodeItem}) {
  if (value is! List) throw ProtocolCodecException(path, 'expected an array');
  return _freezeList<T>(value.indexed.map((entry) => decode(entry.$2, '$path[${entry.$1}]')), path, (item, _) => item, minItems: minItems, uniqueItems: uniqueItems, encodeItem: encodeItem);
}

const int coreSchemaVersion = 1;

typedef ClientId = String;

ClientId decodeClientId(Object? value, {String path = 'ClientId'}) => _string(value, path, minLength: 1);
Object? encodeClientId(ClientId value, {String path = 'ClientId'}) {
  final checked = _string(value, path, minLength: 1);
  return checked;
}

typedef Cursor = String;

Cursor decodeCursor(Object? value, {String path = 'Cursor'}) => _string(value, path, minLength: 1);
Object? encodeCursor(Cursor value, {String path = 'Cursor'}) {
  final checked = _string(value, path, minLength: 1);
  return checked;
}

final class DeviceDescriptor {
  factory DeviceDescriptor({
    required String deviceName,
    required String operatingSystem,
    required String systemVersion,
  }) {
    final validatedDeviceName = _string(deviceName, 'DeviceDescriptor.deviceName', minLength: 1);
    final validatedOperatingSystem = _string(operatingSystem, 'DeviceDescriptor.operatingSystem', minLength: 1);
    final validatedSystemVersion = _string(systemVersion, 'DeviceDescriptor.systemVersion', minLength: 1);
    return DeviceDescriptor._(
      deviceName: validatedDeviceName,
      operatingSystem: validatedOperatingSystem,
      systemVersion: validatedSystemVersion,
    );
  }

  DeviceDescriptor._({
    required this.deviceName,
    required this.operatingSystem,
    required this.systemVersion,
  });

  final String deviceName;
  final String operatingSystem;
  final String systemVersion;

  factory DeviceDescriptor.fromJson(Object? value, {String path = 'DeviceDescriptor'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'deviceName', 'operatingSystem', 'systemVersion'}, path);
    return DeviceDescriptor(
      deviceName: _string(_required(json, 'deviceName', path), '$path.deviceName', minLength: 1),
      operatingSystem: _string(_required(json, 'operatingSystem', path), '$path.operatingSystem', minLength: 1),
      systemVersion: _string(_required(json, 'systemVersion', path), '$path.systemVersion', minLength: 1),
    );
  }

  Map<String, Object?> toJson() => {
    'deviceName': deviceName,
    'operatingSystem': operatingSystem,
    'systemVersion': systemVersion,
  };

  @override
  String toString() => 'DeviceDescriptor(deviceName: $deviceName, operatingSystem: $operatingSystem, systemVersion: $systemVersion)';
}

typedef DeviceId = String;

DeviceId decodeDeviceId(Object? value, {String path = 'DeviceId'}) => _string(value, path, minLength: 1);
Object? encodeDeviceId(DeviceId value, {String path = 'DeviceId'}) {
  final checked = _string(value, path, minLength: 1);
  return checked;
}

typedef EventCursor = String;

EventCursor decodeEventCursor(Object? value, {String path = 'EventCursor'}) => _string(value, path, minLength: 1);
Object? encodeEventCursor(EventCursor value, {String path = 'EventCursor'}) {
  final checked = _string(value, path, minLength: 1);
  return checked;
}

typedef EventSequence = int;

EventSequence decodeEventSequence(Object? value, {String path = 'EventSequence'}) => _integer(value, path, minimum: 0, maximum: 9007199254740991);
Object? encodeEventSequence(EventSequence value, {String path = 'EventSequence'}) {
  final checked = _integer(value, path, minimum: 0, maximum: 9007199254740991);
  return checked;
}

typedef JsonObject = Map<String, Object?>;

JsonObject decodeJsonObject(Object? value, {String path = 'JsonObject'}) => _jsonObject(value, path);
Object? encodeJsonObject(JsonObject value, {String path = 'JsonObject'}) {
  final checked = _jsonObject(value, path);
  return _encodeJsonObject(checked, path);
}

typedef NativeResourceId = String;

NativeResourceId decodeNativeResourceId(Object? value, {String path = 'NativeResourceId'}) => _string(value, path, minLength: 1);
Object? encodeNativeResourceId(NativeResourceId value, {String path = 'NativeResourceId'}) {
  final checked = _string(value, path, minLength: 1);
  return checked;
}

final class PageInfo {
  factory PageInfo({
    Cursor? nextCursor,
  }) {
    final validatedNextCursor = nextCursor == null ? null : _string(nextCursor, 'PageInfo.nextCursor', minLength: 1);
    return PageInfo._(
      nextCursor: validatedNextCursor,
    );
  }

  PageInfo._({
    required this.nextCursor,
  });

  final Cursor? nextCursor;

  factory PageInfo.fromJson(Object? value, {String path = 'PageInfo'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'nextCursor'}, path);
    return PageInfo(
      nextCursor: json.containsKey('nextCursor') && json['nextCursor'] != null ? _string(json['nextCursor'], '$path.nextCursor', minLength: 1) : null,
    );
  }

  Map<String, Object?> toJson() => {
    if (nextCursor != null) 'nextCursor': nextCursor!,
  };

  @override
  String toString() => 'PageInfo(nextCursor: $nextCursor)';
}

final class PageRequest {
  factory PageRequest({
    Cursor? cursor,
    int? limit,
  }) {
    final validatedCursor = cursor == null ? null : _string(cursor, 'PageRequest.cursor', minLength: 1);
    final validatedLimit = limit == null ? null : _integer(limit, 'PageRequest.limit', minimum: 1, maximum: 100);
    return PageRequest._(
      cursor: validatedCursor,
      limit: validatedLimit,
    );
  }

  PageRequest._({
    required this.cursor,
    required this.limit,
  });

  final Cursor? cursor;
  final int? limit;

  factory PageRequest.fromJson(Object? value, {String path = 'PageRequest'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'cursor', 'limit'}, path);
    return PageRequest(
      cursor: json.containsKey('cursor') && json['cursor'] != null ? _string(json['cursor'], '$path.cursor', minLength: 1) : null,
      limit: json.containsKey('limit') && json['limit'] != null ? _integer(json['limit'], '$path.limit', minimum: 1, maximum: 100) : null,
    );
  }

  Map<String, Object?> toJson() => {
    if (cursor != null) 'cursor': cursor!,
    if (limit != null) 'limit': limit!,
  };

  @override
  String toString() => 'PageRequest(cursor: $cursor, limit: $limit)';
}

final class ProtocolError {
  factory ProtocolError({
    required String code,
    required String message,
    required bool retryable,
    JsonObject? details,
  }) {
    final validatedCode = _string(code, 'ProtocolError.code', minLength: 1);
    final validatedMessage = _string(message, 'ProtocolError.message', minLength: 1);
    final validatedRetryable = retryable;
    final validatedDetails = details == null ? null : _jsonObject(details, 'ProtocolError.details');
    return ProtocolError._(
      code: validatedCode,
      message: validatedMessage,
      retryable: validatedRetryable,
      details: validatedDetails,
    );
  }

  ProtocolError._({
    required this.code,
    required this.message,
    required this.retryable,
    required this.details,
  });

  final String code;
  final String message;
  final bool retryable;
  final JsonObject? details;

  factory ProtocolError.fromJson(Object? value, {String path = 'ProtocolError'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'code', 'message', 'retryable', 'details'}, path);
    return ProtocolError(
      code: _string(_required(json, 'code', path), '$path.code', minLength: 1),
      message: _string(_required(json, 'message', path), '$path.message', minLength: 1),
      retryable: _boolean(_required(json, 'retryable', path), '$path.retryable'),
      details: json.containsKey('details') && json['details'] != null ? _jsonObject(json['details'], '$path.details') : null,
    );
  }

  Map<String, Object?> toJson() => {
    'code': code,
    'message': message,
    'retryable': retryable,
    if (details != null) 'details': _encodeJsonObject(details!, 'ProtocolError.details'),
  };

  @override
  String toString() => 'ProtocolError(code: $code, message: $message, retryable: $retryable, details: $details)';
}

typedef ProtocolVersion = int;

ProtocolVersion decodeProtocolVersion(Object? value, {String path = 'ProtocolVersion'}) => _integer(value, path, minimum: 0, maximum: 4294967295);
Object? encodeProtocolVersion(ProtocolVersion value, {String path = 'ProtocolVersion'}) {
  final checked = _integer(value, path, minimum: 0, maximum: 4294967295);
  return checked;
}

typedef ProviderInstanceId = String;

ProviderInstanceId decodeProviderInstanceId(Object? value, {String path = 'ProviderInstanceId'}) => _string(value, path, minLength: 1);
Object? encodeProviderInstanceId(ProviderInstanceId value, {String path = 'ProviderInstanceId'}) {
  final checked = _string(value, path, minLength: 1);
  return checked;
}

typedef ProviderPluginId = String;

ProviderPluginId decodeProviderPluginId(Object? value, {String path = 'ProviderPluginId'}) => _string(value, path, minLength: 1);
Object? encodeProviderPluginId(ProviderPluginId value, {String path = 'ProviderPluginId'}) {
  final checked = _string(value, path, minLength: 1);
  return checked;
}

typedef RequestId = String;

RequestId decodeRequestId(Object? value, {String path = 'RequestId'}) => _string(value, path, minLength: 1);
Object? encodeRequestId(RequestId value, {String path = 'RequestId'}) {
  final checked = _string(value, path, minLength: 1);
  return checked;
}

final class RoutedResourceId {
  factory RoutedResourceId({
    required String providerId,
    required NativeResourceId nativeResourceId,
  }) {
    final validatedProviderId = _string(providerId, 'RoutedResourceId.providerId', minLength: 1);
    final validatedNativeResourceId = _string(nativeResourceId, 'RoutedResourceId.nativeResourceId', minLength: 1);
    return RoutedResourceId._(
      providerId: validatedProviderId,
      nativeResourceId: validatedNativeResourceId,
    );
  }

  RoutedResourceId._({
    required this.providerId,
    required this.nativeResourceId,
  });

  final String providerId;
  final NativeResourceId nativeResourceId;

  factory RoutedResourceId.fromJson(Object? value, {String path = 'RoutedResourceId'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'providerId', 'nativeResourceId'}, path);
    return RoutedResourceId(
      providerId: _string(_required(json, 'providerId', path), '$path.providerId', minLength: 1),
      nativeResourceId: _string(_required(json, 'nativeResourceId', path), '$path.nativeResourceId', minLength: 1),
    );
  }

  Map<String, Object?> toJson() => {
    'providerId': providerId,
    'nativeResourceId': nativeResourceId,
  };

  @override
  String toString() => 'RoutedResourceId(providerId: $providerId, nativeResourceId: $nativeResourceId)';
}

final class RpcError {
  factory RpcError({
    required int code,
    required String message,
    JsonObject? data,
  }) {
    final validatedCode = _integer(code, 'RpcError.code');
    final validatedMessage = _string(message, 'RpcError.message', minLength: 1);
    final validatedData = data == null ? null : _jsonObject(data, 'RpcError.data');
    return RpcError._(
      code: validatedCode,
      message: validatedMessage,
      data: validatedData,
    );
  }

  RpcError._({
    required this.code,
    required this.message,
    required this.data,
  });

  final int code;
  final String message;
  final JsonObject? data;

  factory RpcError.fromJson(Object? value, {String path = 'RpcError'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'code', 'message', 'data'}, path);
    return RpcError(
      code: _integer(_required(json, 'code', path), '$path.code'),
      message: _string(_required(json, 'message', path), '$path.message', minLength: 1),
      data: json.containsKey('data') && json['data'] != null ? _jsonObject(json['data'], '$path.data') : null,
    );
  }

  Map<String, Object?> toJson() => {
    'code': code,
    'message': message,
    if (data != null) 'data': _encodeJsonObject(data!, 'RpcError.data'),
  };

  @override
  String toString() => 'RpcError(code: $code, message: $message, data: $data)';
}

typedef TimestampMs = int;

TimestampMs decodeTimestampMs(Object? value, {String path = 'TimestampMs'}) => _integer(value, path, minimum: 0, maximum: 9007199254740991);
Object? encodeTimestampMs(TimestampMs value, {String path = 'TimestampMs'}) {
  final checked = _integer(value, path, minimum: 0, maximum: 9007199254740991);
  return checked;
}

final class TraceContext {
  factory TraceContext({
    required String traceparent,
    String? tracestate,
  }) {
    final validatedTraceparent = _string(traceparent, 'TraceContext.traceparent', pattern: '^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}\$');
    final validatedTracestate = tracestate == null ? null : _string(tracestate, 'TraceContext.tracestate', minLength: 1);
    return TraceContext._(
      traceparent: validatedTraceparent,
      tracestate: validatedTracestate,
    );
  }

  TraceContext._({
    required this.traceparent,
    required this.tracestate,
  });

  final String traceparent;
  final String? tracestate;

  factory TraceContext.fromJson(Object? value, {String path = 'TraceContext'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'traceparent', 'tracestate'}, path);
    return TraceContext(
      traceparent: _string(_required(json, 'traceparent', path), '$path.traceparent', pattern: '^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}\$'),
      tracestate: json.containsKey('tracestate') && json['tracestate'] != null ? _string(json['tracestate'], '$path.tracestate', minLength: 1) : null,
    );
  }

  Map<String, Object?> toJson() => {
    'traceparent': traceparent,
    if (tracestate != null) 'tracestate': tracestate!,
  };

  @override
  String toString() => 'TraceContext(traceparent: $traceparent, tracestate: $tracestate)';
}

final class VersionRange {
  factory VersionRange({
    required ProtocolVersion minVersion,
    required ProtocolVersion maxVersion,
  }) {
    final validatedMinVersion = _integer(minVersion, 'VersionRange.minVersion', minimum: 0, maximum: 4294967295);
    final validatedMaxVersion = _integer(maxVersion, 'VersionRange.maxVersion', minimum: 0, maximum: 4294967295);
    return VersionRange._(
      minVersion: validatedMinVersion,
      maxVersion: validatedMaxVersion,
    );
  }

  VersionRange._({
    required this.minVersion,
    required this.maxVersion,
  });

  final ProtocolVersion minVersion;
  final ProtocolVersion maxVersion;

  factory VersionRange.fromJson(Object? value, {String path = 'VersionRange'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'minVersion', 'maxVersion'}, path);
    return VersionRange(
      minVersion: _integer(_required(json, 'minVersion', path), '$path.minVersion', minimum: 0, maximum: 4294967295),
      maxVersion: _integer(_required(json, 'maxVersion', path), '$path.maxVersion', minimum: 0, maximum: 4294967295),
    );
  }

  Map<String, Object?> toJson() => {
    'minVersion': minVersion,
    'maxVersion': maxVersion,
  };

  @override
  String toString() => 'VersionRange(minVersion: $minVersion, maxVersion: $maxVersion)';
}
