// @generated by tools/protocol-codegen/generate.mjs from protocol/channel/lan/v1/manifest.json and protocol/channel/lan/v1/schema.json.
// DO NOT EDIT MANUALLY.
// ignore_for_file: unused_element

import 'dart:convert';
import 'package:codepet_core_sdk/codepet_core_sdk.dart';

Map<String, Object?> _object(Object? value, String path) {
  if (value is! Map) throw ProtocolCodecException(path, 'expected an object');
  final result = <String, Object?>{};
  for (final entry in value.entries) {
    if (entry.key is! String) throw ProtocolCodecException(path, 'object keys must be strings');
    result[entry.key as String] = entry.value;
  }
  return result;
}

void _expectKeys(Map<String, Object?> value, Set<String> allowed, String path) {
  for (final key in value.keys) {
    if (!allowed.contains(key)) throw ProtocolCodecException('$path.$key', 'unknown field');
  }
}

Object? _required(Map<String, Object?> value, String key, String path) {
  if (!value.containsKey(key)) throw ProtocolCodecException('$path.$key', 'required field is missing');
  return value[key];
}

Object? _nullValue(Object? value, String path) {
  if (value != null) throw ProtocolCodecException(path, 'expected null');
  return null;
}

String _string(Object? value, String path, {int? minLength, String? pattern}) {
  if (value is! String) throw ProtocolCodecException(path, 'expected a string');
  if (minLength != null && value.length < minLength) throw ProtocolCodecException(path, 'string is shorter than $minLength characters');
  if (pattern != null && !RegExp(pattern).hasMatch(value)) throw ProtocolCodecException(path, 'string does not match $pattern');
  return value;
}

int _integer(Object? value, String path, {int? minimum, int? maximum}) {
  if (value is! int) throw ProtocolCodecException(path, 'expected an integer');
  if (minimum != null && value < minimum) throw ProtocolCodecException(path, 'integer is below $minimum');
  if (maximum != null && value > maximum) throw ProtocolCodecException(path, 'integer is above $maximum');
  return value;
}

bool _boolean(Object? value, String path) {
  if (value is! bool) throw ProtocolCodecException(path, 'expected a boolean');
  return value;
}

Object? _jsonValue(Object? value, String path) {
  if (value == null || value is bool || value is num || value is String) return value;
  if (value is List) {
    return List<Object?>.unmodifiable(value.indexed.map((entry) => _jsonValue(entry.$2, '$path[${entry.$1}]')));
  }
  if (value is Map) {
    return Map<String, Object?>.unmodifiable(_object(value, path).map((key, item) => MapEntry(key, _jsonValue(item, '$path.$key'))));
  }
  throw ProtocolCodecException(path, 'expected a JSON value');
}

Map<String, Object?> _jsonObject(Object? value, String path) => _jsonValue(_object(value, path), path) as Map<String, Object?>;
Map<String, Object?> _encodeJsonObject(Map<String, Object?> value, String path) => _jsonObject(value, path);

List<T> _freezeList<T>(Iterable<T> values, String path, T Function(T, String) validate, {int? minItems, bool uniqueItems = false, required Object? Function(T) encodeItem}) {
  final result = List<T>.unmodifiable(values.indexed.map((entry) => validate(entry.$2, '$path[${entry.$1}]')));
  if (minItems != null && result.length < minItems) throw ProtocolCodecException(path, 'array has fewer than $minItems items');
  if (uniqueItems) {
    final encoded = result.map((item) => jsonEncode(encodeItem(item))).toSet();
    if (encoded.length != result.length) throw ProtocolCodecException(path, 'array contains duplicate items');
  }
  return result;
}

List<T> _decodeList<T>(Object? value, String path, T Function(Object?, String) decode, {int? minItems, bool uniqueItems = false, required Object? Function(T) encodeItem}) {
  if (value is! List) throw ProtocolCodecException(path, 'expected an array');
  return _freezeList<T>(value.indexed.map((entry) => decode(entry.$2, '$path[${entry.$1}]')), path, (item, _) => item, minItems: minItems, uniqueItems: uniqueItems, encodeItem: encodeItem);
}

const int channelLanSchemaVersion = 1;

final class CurrentCredentialDeleteResponse {
  factory CurrentCredentialDeleteResponse({
    required bool revoked,
  }) {
    final validatedRevoked = revoked;
    return CurrentCredentialDeleteResponse._(
      revoked: validatedRevoked,
    );
  }

  CurrentCredentialDeleteResponse._({
    required this.revoked,
  });

  final bool revoked;

  factory CurrentCredentialDeleteResponse.fromJson(Object? value, {String path = 'CurrentCredentialDeleteResponse'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'revoked'}, path);
    return CurrentCredentialDeleteResponse(
      revoked: _boolean(_required(json, 'revoked', path), '$path.revoked'),
    );
  }

  Map<String, Object?> toJson() => {
    'revoked': revoked,
  };

  @override
  String toString() => 'CurrentCredentialDeleteResponse(revoked: $revoked)';
}

final class LanHostIdentity {
  factory LanHostIdentity({
    required DeviceId deviceId,
    required DeviceDescriptor descriptor,
    required String identityFingerprint,
  }) {
    final validatedDeviceId = _string(deviceId, 'LanHostIdentity.deviceId', minLength: 1);
    final validatedDescriptor = descriptor;
    final validatedIdentityFingerprint = _string(identityFingerprint, 'LanHostIdentity.identityFingerprint', pattern: '^[0-9a-f]{64}\$');
    return LanHostIdentity._(
      deviceId: validatedDeviceId,
      descriptor: validatedDescriptor,
      identityFingerprint: validatedIdentityFingerprint,
    );
  }

  LanHostIdentity._({
    required this.deviceId,
    required this.descriptor,
    required this.identityFingerprint,
  });

  final DeviceId deviceId;
  final DeviceDescriptor descriptor;
  final String identityFingerprint;

  factory LanHostIdentity.fromJson(Object? value, {String path = 'LanHostIdentity'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'deviceId', 'descriptor', 'identityFingerprint'}, path);
    return LanHostIdentity(
      deviceId: _string(_required(json, 'deviceId', path), '$path.deviceId', minLength: 1),
      descriptor: DeviceDescriptor.fromJson(_required(json, 'descriptor', path), path: '$path.descriptor'),
      identityFingerprint: _string(_required(json, 'identityFingerprint', path), '$path.identityFingerprint', pattern: '^[0-9a-f]{64}\$'),
    );
  }

  Map<String, Object?> toJson() => {
    'deviceId': deviceId,
    'descriptor': descriptor.toJson(),
    'identityFingerprint': identityFingerprint,
  };

  @override
  String toString() => 'LanHostIdentity(deviceId: $deviceId, descriptor: $descriptor, identityFingerprint: $identityFingerprint)';
}

final class PairingExchangeRequest {
  factory PairingExchangeRequest({
    required String pairingSecret,
    required ClientId clientId,
    required DeviceDescriptor device,
  }) {
    final validatedPairingSecret = _string(pairingSecret, 'PairingExchangeRequest.pairingSecret', pattern: '^[0-9a-f]{64}\$');
    final validatedClientId = _string(clientId, 'PairingExchangeRequest.clientId', minLength: 1);
    final validatedDevice = device;
    return PairingExchangeRequest._(
      pairingSecret: validatedPairingSecret,
      clientId: validatedClientId,
      device: validatedDevice,
    );
  }

  PairingExchangeRequest._({
    required this.pairingSecret,
    required this.clientId,
    required this.device,
  });

  final String pairingSecret;
  final ClientId clientId;
  final DeviceDescriptor device;

  factory PairingExchangeRequest.fromJson(Object? value, {String path = 'PairingExchangeRequest'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'pairingSecret', 'clientId', 'device'}, path);
    return PairingExchangeRequest(
      pairingSecret: _string(_required(json, 'pairingSecret', path), '$path.pairingSecret', pattern: '^[0-9a-f]{64}\$'),
      clientId: _string(_required(json, 'clientId', path), '$path.clientId', minLength: 1),
      device: DeviceDescriptor.fromJson(_required(json, 'device', path), path: '$path.device'),
    );
  }

  Map<String, Object?> toJson() => {
    'pairingSecret': pairingSecret,
    'clientId': clientId,
    'device': device.toJson(),
  };

  @override
  String toString() => 'PairingExchangeRequest(pairingSecret: <redacted>, clientId: $clientId, device: $device)';
}

final class PairingExchangeResponse {
  factory PairingExchangeResponse({
    required LanHostIdentity device,
    required String gatewayUrl,
    required String credential,
  }) {
    final validatedDevice = device;
    final validatedGatewayUrl = _string(gatewayUrl, 'PairingExchangeResponse.gatewayUrl', minLength: 1);
    final validatedCredential = _string(credential, 'PairingExchangeResponse.credential', minLength: 1);
    return PairingExchangeResponse._(
      device: validatedDevice,
      gatewayUrl: validatedGatewayUrl,
      credential: validatedCredential,
    );
  }

  PairingExchangeResponse._({
    required this.device,
    required this.gatewayUrl,
    required this.credential,
  });

  final LanHostIdentity device;
  final String gatewayUrl;
  final String credential;

  factory PairingExchangeResponse.fromJson(Object? value, {String path = 'PairingExchangeResponse'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'device', 'gatewayUrl', 'credential'}, path);
    return PairingExchangeResponse(
      device: LanHostIdentity.fromJson(_required(json, 'device', path), path: '$path.device'),
      gatewayUrl: _string(_required(json, 'gatewayUrl', path), '$path.gatewayUrl', minLength: 1),
      credential: _string(_required(json, 'credential', path), '$path.credential', minLength: 1),
    );
  }

  Map<String, Object?> toJson() => {
    'device': device.toJson(),
    'gatewayUrl': gatewayUrl,
    'credential': credential,
  };

  @override
  String toString() => 'PairingExchangeResponse(device: $device, gatewayUrl: $gatewayUrl, credential: <redacted>)';
}

final class PairingQrPayload {
  factory PairingQrPayload({
    required int version,
    required DeviceId hostDeviceId,
    required String displayName,
    required String httpsBaseUrl,
    required String certSha256,
    required String pairingId,
    required String pairingSecret,
    required TimestampMs expiresAt,
  }) {
    final validatedVersion = _integer(version, 'PairingQrPayload.version', minimum: 1, maximum: 1);
    final validatedHostDeviceId = _string(hostDeviceId, 'PairingQrPayload.hostDeviceId', minLength: 1);
    final validatedDisplayName = _string(displayName, 'PairingQrPayload.displayName', minLength: 1);
    final validatedHttpsBaseUrl = _string(httpsBaseUrl, 'PairingQrPayload.httpsBaseUrl', minLength: 1);
    final validatedCertSha256 = _string(certSha256, 'PairingQrPayload.certSha256', pattern: '^[0-9a-f]{64}\$');
    final validatedPairingId = _string(pairingId, 'PairingQrPayload.pairingId', minLength: 1);
    final validatedPairingSecret = _string(pairingSecret, 'PairingQrPayload.pairingSecret', pattern: '^[0-9a-f]{64}\$');
    final validatedExpiresAt = _integer(expiresAt, 'PairingQrPayload.expiresAt', minimum: 0, maximum: 9007199254740991);
    return PairingQrPayload._(
      version: validatedVersion,
      hostDeviceId: validatedHostDeviceId,
      displayName: validatedDisplayName,
      httpsBaseUrl: validatedHttpsBaseUrl,
      certSha256: validatedCertSha256,
      pairingId: validatedPairingId,
      pairingSecret: validatedPairingSecret,
      expiresAt: validatedExpiresAt,
    );
  }

  PairingQrPayload._({
    required this.version,
    required this.hostDeviceId,
    required this.displayName,
    required this.httpsBaseUrl,
    required this.certSha256,
    required this.pairingId,
    required this.pairingSecret,
    required this.expiresAt,
  });

  final int version;
  final DeviceId hostDeviceId;
  final String displayName;
  final String httpsBaseUrl;
  final String certSha256;
  final String pairingId;
  final String pairingSecret;
  final TimestampMs expiresAt;

  factory PairingQrPayload.fromJson(Object? value, {String path = 'PairingQrPayload'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'version', 'hostDeviceId', 'displayName', 'httpsBaseUrl', 'certSha256', 'pairingId', 'pairingSecret', 'expiresAt'}, path);
    return PairingQrPayload(
      version: _integer(_required(json, 'version', path), '$path.version', minimum: 1, maximum: 1),
      hostDeviceId: _string(_required(json, 'hostDeviceId', path), '$path.hostDeviceId', minLength: 1),
      displayName: _string(_required(json, 'displayName', path), '$path.displayName', minLength: 1),
      httpsBaseUrl: _string(_required(json, 'httpsBaseUrl', path), '$path.httpsBaseUrl', minLength: 1),
      certSha256: _string(_required(json, 'certSha256', path), '$path.certSha256', pattern: '^[0-9a-f]{64}\$'),
      pairingId: _string(_required(json, 'pairingId', path), '$path.pairingId', minLength: 1),
      pairingSecret: _string(_required(json, 'pairingSecret', path), '$path.pairingSecret', pattern: '^[0-9a-f]{64}\$'),
      expiresAt: _integer(_required(json, 'expiresAt', path), '$path.expiresAt', minimum: 0, maximum: 9007199254740991),
    );
  }

  Map<String, Object?> toJson() => {
    'version': version,
    'hostDeviceId': hostDeviceId,
    'displayName': displayName,
    'httpsBaseUrl': httpsBaseUrl,
    'certSha256': certSha256,
    'pairingId': pairingId,
    'pairingSecret': pairingSecret,
    'expiresAt': expiresAt,
  };

  @override
  String toString() => 'PairingQrPayload(version: $version, hostDeviceId: $hostDeviceId, displayName: $displayName, httpsBaseUrl: $httpsBaseUrl, certSha256: $certSha256, pairingId: $pairingId, pairingSecret: <redacted>, expiresAt: $expiresAt)';
}

final class PairingRequestCreateRequest {
  factory PairingRequestCreateRequest({
    required DeviceId hostDeviceId,
    required ClientId clientId,
    required DeviceDescriptor device,
    required String clientNonce,
  }) {
    final validatedHostDeviceId = _string(hostDeviceId, 'PairingRequestCreateRequest.hostDeviceId', minLength: 1);
    final validatedClientId = _string(clientId, 'PairingRequestCreateRequest.clientId', minLength: 1);
    final validatedDevice = device;
    final validatedClientNonce = _string(clientNonce, 'PairingRequestCreateRequest.clientNonce', pattern: '^[0-9a-f]{64}\$');
    return PairingRequestCreateRequest._(
      hostDeviceId: validatedHostDeviceId,
      clientId: validatedClientId,
      device: validatedDevice,
      clientNonce: validatedClientNonce,
    );
  }

  PairingRequestCreateRequest._({
    required this.hostDeviceId,
    required this.clientId,
    required this.device,
    required this.clientNonce,
  });

  final DeviceId hostDeviceId;
  final ClientId clientId;
  final DeviceDescriptor device;
  final String clientNonce;

  factory PairingRequestCreateRequest.fromJson(Object? value, {String path = 'PairingRequestCreateRequest'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'hostDeviceId', 'clientId', 'device', 'clientNonce'}, path);
    return PairingRequestCreateRequest(
      hostDeviceId: _string(_required(json, 'hostDeviceId', path), '$path.hostDeviceId', minLength: 1),
      clientId: _string(_required(json, 'clientId', path), '$path.clientId', minLength: 1),
      device: DeviceDescriptor.fromJson(_required(json, 'device', path), path: '$path.device'),
      clientNonce: _string(_required(json, 'clientNonce', path), '$path.clientNonce', pattern: '^[0-9a-f]{64}\$'),
    );
  }

  Map<String, Object?> toJson() => {
    'hostDeviceId': hostDeviceId,
    'clientId': clientId,
    'device': device.toJson(),
    'clientNonce': clientNonce,
  };

  @override
  String toString() => 'PairingRequestCreateRequest(hostDeviceId: $hostDeviceId, clientId: $clientId, device: $device, clientNonce: $clientNonce)';
}

enum PairingRequestState {
  pending('pending'),
  accepted('accepted'),
  rejected('rejected'),
  expired('expired');

  const PairingRequestState(this.wireValue);

  final String wireValue;

  static PairingRequestState fromJson(Object? value, {String path = 'PairingRequestState'}) {
    final wireValue = _string(value, path);
    for (final candidate in values) {
      if (candidate.wireValue == wireValue) return candidate;
    }
    throw ProtocolCodecException(path, 'expected one of: pending, accepted, rejected, expired');
  }

  String toJson() => wireValue;
}

final class PairingRequestStatusResponse {
  factory PairingRequestStatusResponse({
    required String requestId,
    required PairingRequestState state,
    required LanHostIdentity device,
    required TimestampMs expiresAt,
    required String confirmationCode,
    String? gatewayUrl,
    String? credential,
  }) {
    final validatedRequestId = _string(requestId, 'PairingRequestStatusResponse.requestId', minLength: 1);
    final validatedState = state;
    final validatedDevice = device;
    final validatedExpiresAt = _integer(expiresAt, 'PairingRequestStatusResponse.expiresAt', minimum: 0, maximum: 9007199254740991);
    final validatedConfirmationCode = _string(confirmationCode, 'PairingRequestStatusResponse.confirmationCode', pattern: '^[0-9]{6}\$');
    final validatedGatewayUrl = gatewayUrl == null ? null : _string(gatewayUrl, 'PairingRequestStatusResponse.gatewayUrl', minLength: 1);
    final validatedCredential = credential == null ? null : _string(credential, 'PairingRequestStatusResponse.credential', minLength: 1);
    return PairingRequestStatusResponse._(
      requestId: validatedRequestId,
      state: validatedState,
      device: validatedDevice,
      expiresAt: validatedExpiresAt,
      confirmationCode: validatedConfirmationCode,
      gatewayUrl: validatedGatewayUrl,
      credential: validatedCredential,
    );
  }

  PairingRequestStatusResponse._({
    required this.requestId,
    required this.state,
    required this.device,
    required this.expiresAt,
    required this.confirmationCode,
    required this.gatewayUrl,
    required this.credential,
  });

  final String requestId;
  final PairingRequestState state;
  final LanHostIdentity device;
  final TimestampMs expiresAt;
  final String confirmationCode;
  final String? gatewayUrl;
  final String? credential;

  factory PairingRequestStatusResponse.fromJson(Object? value, {String path = 'PairingRequestStatusResponse'}) {
    final json = _object(value, path);
    _expectKeys(json, const {'requestId', 'state', 'device', 'expiresAt', 'confirmationCode', 'gatewayUrl', 'credential'}, path);
    return PairingRequestStatusResponse(
      requestId: _string(_required(json, 'requestId', path), '$path.requestId', minLength: 1),
      state: PairingRequestState.fromJson(_required(json, 'state', path), path: '$path.state'),
      device: LanHostIdentity.fromJson(_required(json, 'device', path), path: '$path.device'),
      expiresAt: _integer(_required(json, 'expiresAt', path), '$path.expiresAt', minimum: 0, maximum: 9007199254740991),
      confirmationCode: _string(_required(json, 'confirmationCode', path), '$path.confirmationCode', pattern: '^[0-9]{6}\$'),
      gatewayUrl: json.containsKey('gatewayUrl') && json['gatewayUrl'] != null ? _string(json['gatewayUrl'], '$path.gatewayUrl', minLength: 1) : null,
      credential: json.containsKey('credential') && json['credential'] != null ? _string(json['credential'], '$path.credential', minLength: 1) : null,
    );
  }

  Map<String, Object?> toJson() => {
    'requestId': requestId,
    'state': state.toJson(),
    'device': device.toJson(),
    'expiresAt': expiresAt,
    'confirmationCode': confirmationCode,
    if (gatewayUrl != null) 'gatewayUrl': gatewayUrl!,
    if (credential != null) 'credential': credential!,
  };

  @override
  String toString() => 'PairingRequestStatusResponse(requestId: $requestId, state: $state, device: $device, expiresAt: $expiresAt, confirmationCode: $confirmationCode, gatewayUrl: $gatewayUrl, credential: <redacted>)';
}
